apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
  - name: busybox-container
    image: {{ .Values.image.repository }}
    command:
    - /bin/sh
    args:
    - -c
    - while true; do echo "Hello, World!"; sleep 10; done