apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
  - name: busybox-container
    image: docker.io/busybox:1.36
    command:
    - /bin/sh
    args:
    - -c
    - while true; do echo "Hello, World!"; sleep 10; done
    resources:
      requests:
        memory: 128Mi
        cpu: 250m
      limits:
        memory: 128Mi
        cpu: 250m
    livenessProbe:
      exec:
        command:
        - ls
        - /
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      exec:
        command:
        - ls
        - /
      initialDelaySeconds: 30
      periodSeconds: 10
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
