apiVersion: v1
kind: Secret
metadata:
  name: release-name-nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-3.5.13
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  nextcloud-username: YWRtaW4=
  nextcloud-password: Y2hhbmdlbWU=
  nextcloud-token: c3g2a2lscnNyRA==
---
apiVersion: v1
kind: Service
metadata:
  name: release-name-nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-3.5.13
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-3.5.13
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: app
      annotations:
        nextcloud-config-hash: a5aae02b1b8278a9c8a2dc143e82d3737fc295f62c34afd617207f37d1b2b438
        php-config-hash: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
        container.apparmor.security.beta.kubernetes.io/nextcloud: runtime/default
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:27.0-fpm@sha256:ec6a912bf5100c8cf2d9cbc2c318fb37c34cf25048126fd9ceaac69164067b26
        imagePullPolicy: IfNotPresent
        env:
        - name: SQLITE_DATABASE
          value: nextcloud
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: nextcloud.kube.home
        - name: NEXTCLOUD_DATA_DIR
          value: /var/www/html/data
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status.php
            port: 80
            httpHeaders:
            - name: Host
              value: nextcloud.kube.home
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /status.php
            port: 80
            httpHeaders:
            - name: Host
              value: nextcloud.kube.home
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: nextcloud-main
          mountPath: /var/www/
          subPath: root
        - name: nextcloud-main
          mountPath: /var/www/html
          subPath: html
        - name: nextcloud-main
          mountPath: /var/www/html/data
          subPath: data
        - name: nextcloud-main
          mountPath: /var/www/html/config
          subPath: config
        - name: nextcloud-main
          mountPath: /var/www/html/custom_apps
          subPath: custom_apps
        - name: nextcloud-main
          mountPath: /var/www/tmp
          subPath: tmp
        - name: nextcloud-main
          mountPath: /var/www/html/themes
          subPath: themes
        - name: secret-volume
          readOnly: true
          mountPath: /etc/secret-volume
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 128Mi
            cpu: 250m
        securityContext:
          runAsNonRoot: true
          runAsUser: 25000
          runAsGroup: 25000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      volumes:
      - name: nextcloud-main
        emptyDir: {}
      - name: secret-volume
        secret:
          secretName: my-secret
      securityContext:
        fsGroup: 33
        runAsNonRoot: true
        runAsUser: 25000
        runAsGroup: 25000
        seccompProfile:
          type: RuntimeDefault
