apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-nexus-repository-manager
  labels:
    helm.sh/chart: nexus-repository-manager-55.0.0
    app.kubernetes.io/name: nexus-repository-manager
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 3.55.0
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-nexus-repository-manager-data
  labels:
    helm.sh/chart: nexus-repository-manager-55.0.0
    app.kubernetes.io/name: nexus-repository-manager
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 3.55.0
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: release-name-nexus-repository-manager
  labels:
    helm.sh/chart: nexus-repository-manager-55.0.0
    app.kubernetes.io/name: nexus-repository-manager
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 3.55.0
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 8081
    protocol: TCP
    name: nexus-ui
  selector:
    app.kubernetes.io/name: nexus-repository-manager
    app.kubernetes.io/instance: release-name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-nexus-repository-manager
  labels:
    helm.sh/chart: nexus-repository-manager-55.0.0
    app.kubernetes.io/name: nexus-repository-manager
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 3.55.0
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus-repository-manager
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        checksum/configmap-properties: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      labels:
        app.kubernetes.io/name: nexus-repository-manager
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-nexus-repository-manager
      terminationGracePeriodSeconds: 120
      containers:
      - name: nexus-repository-manager
        image: sonatype/nexus3:3.55.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        lifecycle: null
        env:
        - name: INSTALL4J_ADD_VM_PARAMS
          value: -Xms2703M -Xmx2703M -XX:MaxDirectMemorySize=2703M -XX:+UnlockExperimentalVMOptions
            -XX:+UseCGroupMemoryLimitForHeap -Djava.util.prefs.userRoot=/nexus-data/javaprefs
        - name: NEXUS_SECURITY_RANDOMPASSWORD
          value: 'true'
        ports:
        - name: nexus-ui
          containerPort: 8081
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 6
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 6
          timeoutSeconds: 10
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 128Mi
            cpu: 250m
      securityContext:
        seccompProfile:
          type: RuntimeDefault
