apiVersion: v1
kind: Secret
metadata:
  name: release-name-pgadmin4
  namespace: test-ns
  labels:
    app.kubernetes.io/name: pgadmin4
    helm.sh/chart: pgadmin4-1.15.2
    app.kubernetes.io/version: '7.0'
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  password: U3VwZXJTZWNyZXQ=
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-pgadmin4
  namespace: default
  labels:
    app.kubernetes.io/name: pgadmin4
    helm.sh/chart: pgadmin4-1.15.2
    app.kubernetes.io/version: '7.0'
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: release-name-pgadmin4
  namespace: test-ns
  labels:
    app.kubernetes.io/name: pgadmin4
    helm.sh/chart: pgadmin4-1.15.2
    app.kubernetes.io/version: '7.0'
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: pgadmin4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-pgadmin4
  namespace: test-ns
  labels:
    app.kubernetes.io/name: pgadmin4
    helm.sh/chart: pgadmin4-1.15.2
    app.kubernetes.io/version: '7.0'
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgadmin4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgadmin4
      annotations:
        checksum/secret: 59aee739a7f5c89c5555f4fc7799b9b33cb01e37e7046a22f01ddebcafd69467
        container.apparmor.security.beta.kubernetes.io/pgadmin4: runtime/default
    spec:
      containers:
      - name: pgadmin4
        image: docker.io/dpage/pgadmin4:7.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            port: http
            path: /misc/ping
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            port: http
            path: /misc/ping
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 15
        env:
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          value: 'False'
        - name: PGADMIN_DEFAULT_EMAIL
          value: chart@domain.com
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
          readOnly: true
        - name: secret-volume
          readOnly: true
          mountPath: /etc/secret-volume
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 25000
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsGroup: 25000
          readOnlyRootFilesystem: true
      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: release-name-pgadmin4
      - name: secret-volume
        secret:
          secretName: my-secret
      securityContext:
        fsGroup: 5050
        runAsGroup: 5050
        runAsUser: 25000
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: release-name-pgadmin4-test-connection
  namespace: test-ns
  labels:
    app.kubernetes.io/name: pgadmin4
    helm.sh/chart: pgadmin4-1.15.2
    app.kubernetes.io/version: '7.0'
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: hook-succeeded
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    container.apparmor.security.beta.kubernetes.io/wget: runtime/default
spec:
  securityContext:
    runAsNonRoot: true
    fsGroup: 5051
    runAsGroup: 5051
    runAsUser: 25000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: wget
    image: docker.io/busybox:1-uclibc@sha256:3dcd6bcb75d6ca5b23642482809ea3dbba4de07d277326454f443b9dcb14b012
    imagePullPolicy: IfNotPresent
    env:
    - name: PGADMIN_HOST
      value: release-name-pgadmin4
    - name: PGADMIN_PORT
      value: '80'
    command:
    - /bin/sh
    - -ec
    - 'response=$(wget -qSO - http://${PGADMIN_HOST}:${PGADMIN_PORT} 2>&1)

      check=$(echo $response | grep -c ''200 OK''); echo $check; if [[ $check -gt
      0 ]]; then echo "Response OK"; else exit 1; fi

      '
    resources:
      limits:
        cpu: 250m
        memory: 128Mi
      requests:
        cpu: 250m
        memory: 128Mi
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      runAsUser: 25000
      capabilities:
        drop:
        - ALL
    readinessProbe:
      exec:
        command:
        - ls
        - /
      initialDelaySeconds: 30
      periodSeconds: 10
    livenessProbe:
      exec:
        command:
        - ls
        - /
      initialDelaySeconds: 30
      periodSeconds: 10
  restartPolicy: Never
  serviceAccountName: SAtest0
  automountServiceAccountToken: false
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max-demo-lr
  namespace: test-ns
spec:
  limits:
  - max:
      cpu: 800m
    min:
      cpu: 250m
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max-demo-lr
  namespace: default
spec:
  limits:
  - max:
      cpu: 800m
    min:
      cpu: 250m
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-high
  namespace: test-ns
spec:
  hard:
    cpu: '1000'
    memory: 200Gi
    pods: '10'
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - high
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-high
  namespace: default
spec:
  hard:
    cpu: '1000'
    memory: 200Gi
    pods: '10'
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - high
