apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-promtail
  namespace: default
  labels:
    helm.sh/chart: promtail-6.11.3
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 2.8.2
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: Secret
metadata:
  name: release-name-promtail
  namespace: default
  labels:
    helm.sh/chart: promtail-6.11.3
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 2.8.2
    app.kubernetes.io/managed-by: Helm
stringData:
  promtail.yaml: "server:\n  log_level: info\n  http_listen_port: 3101\nclients:\n\
    \  - url: http://loki-gateway/loki/api/v1/push\npositions:\n  filename: /run/promtail/positions.yaml\n\
    scrape_configs:\n  # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet\
    \ for reference\n  - job_name: kubernetes-pods\n    pipeline_stages:\n      -\
    \ cri: {}\n    kubernetes_sd_configs:\n      - role: pod\n    relabel_configs:\n\
    \      - source_labels:\n          - __meta_kubernetes_pod_controller_name\n \
    \       regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?\n        action: replace\n   \
    \     target_label: __tmp_controller_name\n      - source_labels:\n          -\
    \ __meta_kubernetes_pod_label_app_kubernetes_io_name\n          - __meta_kubernetes_pod_label_app\n\
    \          - __tmp_controller_name\n          - __meta_kubernetes_pod_name\n \
    \       regex: ^;*([^;]+)(;.*)?$\n        action: replace\n        target_label:\
    \ app\n      - source_labels:\n          - __meta_kubernetes_pod_label_app_kubernetes_io_instance\n\
    \          - __meta_kubernetes_pod_label_release\n        regex: ^;*([^;]+)(;.*)?$\n\
    \        action: replace\n        target_label: instance\n      - source_labels:\n\
    \          - __meta_kubernetes_pod_label_app_kubernetes_io_component\n       \
    \   - __meta_kubernetes_pod_label_component\n        regex: ^;*([^;]+)(;.*)?$\n\
    \        action: replace\n        target_label: component\n      - action: replace\n\
    \        source_labels:\n        - __meta_kubernetes_pod_node_name\n        target_label:\
    \ node_name\n      - action: replace\n        source_labels:\n        - __meta_kubernetes_namespace\n\
    \        target_label: namespace\n      - action: replace\n        replacement:\
    \ $1\n        separator: /\n        source_labels:\n        - namespace\n    \
    \    - app\n        target_label: job\n      - action: replace\n        source_labels:\n\
    \        - __meta_kubernetes_pod_name\n        target_label: pod\n      - action:\
    \ replace\n        source_labels:\n        - __meta_kubernetes_pod_container_name\n\
    \        target_label: container\n      - action: replace\n        replacement:\
    \ /var/log/pods/*$1/*.log\n        separator: /\n        source_labels:\n    \
    \    - __meta_kubernetes_pod_uid\n        - __meta_kubernetes_pod_container_name\n\
    \        target_label: __path__\n      - action: replace\n        regex: true/(.*)\n\
    \        replacement: /var/log/pods/*$1/*.log\n        separator: /\n        source_labels:\n\
    \        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash\n\
    \        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash\n      \
    \  - __meta_kubernetes_pod_container_name\n        target_label: __path__\nlimits_config:\n\
    tracing:\n  enabled: false\n"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-name-promtail
  labels:
    helm.sh/chart: promtail-6.11.3
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 2.8.2
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - watch
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-name-promtail
  labels:
    helm.sh/chart: promtail-6.11.3
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 2.8.2
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: release-name-promtail
  namespace: default
roleRef:
  kind: ClusterRole
  name: release-name-promtail
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: release-name-promtail
  namespace: test-ns
  labels:
    helm.sh/chart: promtail-6.11.3
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 2.8.2
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
      app.kubernetes.io/instance: release-name
  updateStrategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: promtail
        app.kubernetes.io/instance: release-name
      annotations:
        checksum/config: d6556952814f57575458de4f7f3940dc5d4d40b9f99069120c3bf1550023eac2
        container.apparmor.security.beta.kubernetes.io/promtail: runtime/default
    spec:
      serviceAccountName: release-name-promtail
      enableServiceLinks: true
      securityContext:
        runAsGroup: 0
        runAsUser: 25000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: promtail
        image: docker.io/grafana/promtail:2.8.2
        imagePullPolicy: IfNotPresent
        args:
        - -config.file=/etc/promtail/promtail.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/promtail
          readOnly: true
        - mountPath: /run/promtail
          name: run
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: containers
          readOnly: true
        - mountPath: /var/log/pods
          name: pods
          readOnly: true
        - name: secret-volume
          readOnly: true
          mountPath: /etc/secret-volume
        env: []
        ports:
        - name: http-metrics
          containerPort: 3101
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 25000
          runAsNonRoot: true
          runAsGroup: 25000
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 128Mi
            cpu: 250m
        livenessProbe:
          exec:
            command:
            - ls
            - /
          initialDelaySeconds: 30
          periodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      volumes:
      - name: config
        secret:
          secretName: release-name-promtail
      - name: secret-volume
        secret:
          secretName: my-secret
