apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanner
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
spec:
  schedule: 15,45 * * * *
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          initContainers:
          - name: check-db-ready
            image: docker.io/artifacthub/postgres:12@sha256:c549ac499c81cd8760e2c1b861a18138763da4e2678f90eb3b64c193f49b641a
            imagePullPolicy: IfNotPresent
            env:
            - name: PGHOST
              value: release-name-postgresql.default
            - name: PGPORT
              value: '5432'
            - name: PGUSER
              value: postgres
            command:
            - sh
            - -c
            - until pg_isready; do echo waiting for database; sleep 2; done;
            resources:
              limits:
                memory: 128Mi
                cpu: 250m
              requests:
                memory: 128Mi
                cpu: 250m
            securityContext:
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 25000
              runAsGroup: 25000
              allowPrivilegeEscalation: false
            readinessProbe:
              exec:
                command:
                - ls
                - /
              initialDelaySeconds: 30
              periodSeconds: 10
            livenessProbe:
              exec:
                command:
                - ls
                - /
              initialDelaySeconds: 30
              periodSeconds: 10
          containers:
          - name: scanner
            image: artifacthub/scanner:v1.14.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: scanner-config
              mountPath: /home/scanner/.cfg
              readOnly: true
            resources:
              limits:
                memory: 128Mi
                cpu: 250m
              requests:
                memory: 128Mi
                cpu: 250m
            securityContext:
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 25000
              runAsGroup: 25000
              allowPrivilegeEscalation: false
            readinessProbe:
              exec:
                command:
                - ls
                - /
              initialDelaySeconds: 30
              periodSeconds: 10
            livenessProbe:
              exec:
                command:
                - ls
                - /
              initialDelaySeconds: 30
              periodSeconds: 10
          volumes:
          - name: scanner-config
            secret:
              secretName: scanner-config
          securityContext:
            runAsNonRoot: true
            runAsUser: 25000
            runAsGroup: 25000
            seccompProfile:
              type: RuntimeDefault