name: Security Metrics Workflow

on:
  workflow_dispatch:
    inputs:

      chart_folder:
        description: 'The path to the Helm Chart folder'
        required: true
        default: 'mysql'
        type: string

      kernel_version:
        description: 'The kernel version used by the K8s cluster worker nodes'
        required: true
        default: '5.4.0'
        type: string

      kubernetes_version:
        description: 'The Kubernetes version used by the K8s cluster'
        required: true
        default: '1.20.0'
        type: string

      resource_path:
        description: 'The path to the YAML document to be analyzed'
        required: true
        default: 'StatefulSet/default/release-name-mysql'
        type: string

      obj_path:
        description: 'The path to the container to be analyzed'
        required: true
        default: 'spec/template/spec/containers/0'
        type: string

jobs:

  check_CVEs:
    uses: ./.github/workflows/check_cves.yaml
    with:
      chart_folder: ${{ inputs.chart_folder }}
      kernel_version: ${{ inputs.kernel_version }}
      kubernetes_version: ${{ inputs.kubernetes_version }}
      resource_path: ${{ inputs.resource_path }}
      obj_path: ${{ inputs.obj_path }}
