name: Run Kubeaudit

on:
  workflow_call:
    inputs:

      iteration:
        required: true
        type: string

      chart_folder:
        required: true
        type: string


jobs:

  run_kubeaudit:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Define template chart folder - original
        if: ${{ inputs.iteration == '1'}}
        run: echo "TEMPLATE=templates/${{ inputs.chart_folder }}_template.yaml" >> $GITHUB_ENV

      - name: Define template chart folder - fixed
        if: ${{ inputs.iteration == '2'}}
        run: echo "TEMPLATE=templates/${{ inputs.chart_folder }}_fixed_template.yaml" >> $GITHUB_ENV

      - name: Define template chart folder - functionalities
        if: ${{ inputs.iteration == '3'}}
        run: echo "TEMPLATE=templates/${{ inputs.chart_folder }}_func_template.yaml" >> $GITHUB_ENV

      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'  

      - name: Install Kubeaudit
        shell: bash
        run: go get -v github.com/Shopify/kubeaudit

      - name: Kubeaudit Debug
        shell: bash
        run: |
          ls -la
          

      - name: Test with Kubeaudit
        shell: bash
        run: kubeaudit all -f "${{ env.TEMPLATE }}" --format json > results_${{ inputs.iteration }}.json

      - name: Print Kubeaudit result
        shell: bash
        run: jq . results_${{ inputs.iteration }}.json

      - name: Upload the JSON results artifact
        uses: actions/upload-artifact@v3
        with:
          name: results_${{ inputs.iteration }}
          path: results_${{ inputs.iteration }}.json
          if-no-files-found: error
