name: Run SonarCloud

on:
  workflow_call:
    inputs:

      iteration:
        required: true
        type: string

      chart_folder:
        required: true
        type: string
    
    secrets:
      
        SONAR_TOKEN: 
          description: 'SonarCloud API token'
          required: true

jobs:

  run_sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Define template chart folder - original
        if: ${{ inputs.iteration == '1'}}
        run: echo "TEMPLATE=templates/${{ inputs.chart_folder }}_template.yaml" >> $GITHUB_ENV

      - name: Define template chart folder - fixed
        if: ${{ inputs.iteration == '2'}}
        run: echo "TEMPLATE=fixed_templates/${{ inputs.chart_folder }}_${{ inputs.first_tool }}_fixed_template.yaml" >> $GITHUB_ENV

      - name: Define template chart folder - functionalities
        if: ${{ inputs.iteration == '3'}}
        run: echo "TEMPLATE=functionality_templates/${{ inputs.chart_folder }}_func_template.yaml" >> $GITHUB_ENV

      - name: Create sonar-project.properties
        shell: bash
        run: |
          echo "sonar.organization=aristsimidakis" > ${{ inputs.chart_folder }}/sonar-project.properties
          echo "sonar.projectKey=ArisTsimidakis_mycharts" >> ${{ inputs.chart_folder }}/sonar-project.properties
          echo "sonar.projectName=mycharts" >> ${{ inputs.chart_folder }}/sonar-project.properties


      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3.1
        with:
          fetch-depth: 0
          projectBaseDir: ${{ inputs.chart_folder }} 
          args: >
            -Dsonar.verbose=true
            -Dsonar.log_level=DEBUG
            -Dsonar.scanner.dumpToFile=sonar-scanner-dump.log
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Fetch SonarCloud Report
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          PROJECT_KEY="ArisTsimidakis_mycharts"
          METRIC_KEYS="alert_status,ncloc,ncloc_language_distribution,projects,new_lines,new_accepted_issues,new_bugs,new_reliability_rating,new_vulnerabilities,new_security_rating,new_security_hotspots,new_security_review_rating, new_security_hotspots_reviewed,new_code_smells,new_maintainability_rating,new_technical_debt,new_coverage, new_lines_to_cover,new_duplicated_lines_density,new_lines,coverage,duplicated_lines_density,new_violations,accepted_issues,bugs,reliability_rating,vulnerabilities,security_rating,security_hotspots,security_review_rating,security_hotspots_reviewed,code_smells,sqale_rating,coverage,lines_to_cover,duplicated_lines_density,lines,violations,maintainability_issues,security_issues,reliability_issues"
          SONAR_API="https://sonarcloud.io/api/measures/component?component=$PROJECT_KEY&metricKeys=$METRIC_KEYS&additionalFields=periods"

          curl --request GET \
            --url $SONAR_API \
            --header "Authorization: Bearer $SONAR_TOKEN" \
            --output "results_${{ inputs.iteration }}.json"
      
      - name: Print SonarCloud result
        shell: bash
        run: jq . results_${{ inputs.iteration }}.json

      - name: Upload the JASON results artifact
        uses: actions/upload-artifact@v2
        with:
          name: results_${{ inputs.iteration }}
          path: results_${{ inputs.iteration }}.json
          if-no-files-found: error
      
      - name: Clean up sonar-project.properties
        shell: bash
        run: rm ${{ inputs.chart_folder }}/sonar-project.properties


      
