name: Run KICS

on:
  workflow_call:
    inputs:

      iteration:
        required: true
        type: string

      chart_folder:
        required: true
        type: string

jobs:

  run_kics:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Define template chart folder - original
        if: ${{ inputs.iteration == '1'}}
        run: echo "TEMPLATE=templates/${{ inputs.chart_folder }}_template.yaml" >> $GITHUB_ENV

      - name: Define template chart folder - fixed
        if: ${{ inputs.iteration == '2'}}
        run: echo "TEMPLATE=fixed_templates/${{ inputs.chart_folder }}_${{ inputs.first_tool }}_fixed_template.yaml" >> $GITHUB_ENV

      - name: Define template chart folder - functionalities
        if: ${{ inputs.iteration == '3'}}
        run: echo "TEMPLATE=functionality_templates/${{ inputs.chart_folder }}_func_template.yaml" >> $GITHUB_ENV

      - name: Run kics Scan
        uses: checkmarx/kics-github-action@v1.6.3
        with:
          path: ${{ env.TEMPLATE }}
          exclude_queries: 487f4be7-3fd9-4506-a07a-eae252180c08
          ignore_on_exit: results
          exclude_severities: 'info'
          output_formats: 'json'
          output_path: .
        # Reference: https://github.com/Checkmarx/kics-github-action
        continue-on-error: true

      - name: Rename KICS results
        shell: bash
        run: mv results.json results_${{ inputs.iteration }}.json

      - name: Print KICS result
        shell: bash
        run: cat results_${{ inputs.iteration }}.json

      - name: Upload the JSON results artifact
        uses: actions/upload-artifact@v3
        with:
          name: results_${{ inputs.iteration }}
          path: results_${{ inputs.iteration }}.json
          if-no-files-found: error
