name: Run Terrascan

on:
  workflow_call:
    inputs:

      iteration:
        required: true
        type: string

      chart_folder:
        required: true
        type: string


jobs:

  run_terrascan:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Define template chart folder - original
        if: ${{ inputs.iteration == '1'}}
        run: echo "TEMPLATE=templates/${{ inputs.chart_folder }}_template.yaml" >> $GITHUB_ENV

      - name: Define template chart folder - fixed
        if: ${{ inputs.iteration == '2'}}
        run: echo "TEMPLATE=templates/${{ inputs.chart_folder }}_fixed_template.yaml" >> $GITHUB_ENV

      - name: Define template chart folder - functionalities
        if: ${{ inputs.iteration == '3'}}
        run: echo "TEMPLATE=templates/${{ inputs.chart_folder }}_func_template.yaml" >> $GITHUB_ENV

      - name: Test with Terrascan
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'k8s'
          iac_dir: '${{ env.TEMPLATE }}'
          iac_version: 'v1'
          policy_type: 'k8s'
          sarif_upload: true
        continue-on-error: true
        # Reference: https://github.com/tenable/terrascan-action

      - name: Rename Terrascan result
        shell: bash
        run: mv terrascan.sarif results_${{ inputs.iteration }}.json

      - name: Print Terrascan result
        shell: bash
        run: jq . results_${{ inputs.iteration }}.json

      - name: Upload the JSON results artifact
        uses: actions/upload-artifact@v3
        with:
          name: results_${{ inputs.iteration }}
          path: results_${{ inputs.iteration }}.json
          if-no-files-found: error
